# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    translator: { fallbacks: ['en'] }
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale: 'en'
    trusted_hosts: ~

    fragments: ~
    http_method_override: true
    assets: ~
