<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($term) {
        $query = $this->createQueryBuilder("a");

        $query
            ->where("LOWER(a.name) LIKE :query")
            ->setParameter("query", "%" . mb_strtolower($term) . "%");

        return $query
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
