<?php

namespace AppBundle\Repository;

/**
 * ConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEmpty() {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT count(c) FROM AppBundle:Conference c WHERE 0 = (SELECT count(r) FROM AppBundle:Reference r WHERE c = r.conference)");

        return $query->getSingleScalarResult();
    }
}
