<?php

namespace AppBundle\Repository;

/**
 * FavouriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends \Doctrine\ORM\EntityRepository
{
}
