imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false

sentry:
    dsn: "%sentry_dsn%"
    options:
        environment: "%sentry_environment%"
        send_default_pii: true
        excluded_exceptions:
            - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'

