#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
